### ISSUE TITLE
on windows build ,is it can build on windows?

### ISSUE THREAD

**Issue by wangjiashuaicpp** [nyu-systems/Grendel-GS#37]
C:\code\Grendel-GS\submodules\diff-gaussian-rasterization\cuda_rasterizer\rasterizer_impl.cu(781): error: expected a "]"

      C:\code\Grendel-GS\submodules\diff-gaussian-rasterization\cuda_rasterizer\rasterizer_impl.cu(781): warning #2409-D: nonstandard use of "auto" to both deduce the type from an initializer and to announce a trailing return type

      C:\code\Grendel-GS\submodules\diff-gaussian-rasterization\cuda_rasterizer\rasterizer_impl.cu(781): error: cannot deduce "auto" type (initializer required)

      C:\code\Grendel-GS\submodules\diff-gaussian-rasterization\cuda_rasterizer\rasterizer_impl.cu(781): error: expected a ";"

      22 errors detected in the compilation of "C:/code/Grendel-GS/submodules/diff-gaussian-rasterization/cuda_rasterizer/rasterizer_impl.cu".
      rasterizer_impl.cu
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\site-packages\torch\utils\cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\code\Grendel-GS\submodules\diff-gaussian-rasterization\setup.py", line 36, in <module>
          'build_ext': BuildExtension
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\wjs\.conda\envs\Grendel-GS2\lib\distutils\dist.py", line 985, in run_command

**Comment by WWaynee** [comment]
In your C:\Users\wjs\.conda\envs\Grendel-GS2\lib\site-packages\torch\utils\cpp_extension.py
modify self.use_ninja = kwargs.get('use_ninja', True) to self.use_ninja = kwargs.get('use_ninja', False)
