### ISSUE TITLE
OOM Error when training NeRF360 Bicycle Dataset

### ISSUE THREAD

**Issue by GBncywang** [nyu-systems/Grendel-GS#41]
When using Grendel to train on the NeRF360 Bicycle dataset (194 images, 9.45 GB), I encounter an OOM error when trying to run the sample training command with 4 GPU and a Batch Size of 4. This data runs fine at native resolution on the original 3DGS training code.

```
torchrun --standalone --nnodes=1 --nproc-per-node=4 train.py --bsz 4 -s ../data/NeRF360/bicycle/undistorted --eval
```

There are some initial errors regarding setting GPU barrier to rank, unsure if this is an issue. 

```
[rank0]:[W1225 01:04:45.574901746 ProcessGroupNCCL.cpp:4115] [PG ID 0 PG GUID 0 Rank 0]  using GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device,or call init_process_group() with a device_id.
```

After it finishes loading camera from disk, it then begins the "Decode Training Camera" step and begins to preload dataset to GPU. This seems to only load a subset of the images (169 out of 194?) and quickly results in a OOM error.

```
Decoding Training Cameras [25/12 01:14:44]
[NOTE]: Preloading dataset(9.458987592GB) to GPU. Disable local_sampling and distributed_dataset_storage. [25/12 01:14:44]
  0%|                                                                  | 0/169 [00:00<?, ?it/s][NOTE]: Preloading dataset(9.458987592GB) to GPU. Disable local_sampling and distributed_dataset_storage. [25/12 01:14:44]
[NOTE]: Preloading dataset(9.458987592GB) to GPU. Disable local_sampling and distributed_dataset_storage. [25/12 01:14:44]
100%|████████████████████████████████████████████████████████| 169/169 [00:18<00:00,  9.26it/s]
 75%|██████████████████████████████████████████              | 127/169 [00:02<00:00, 50.12it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/Grendel-GS/train.py", line 82, in <module>
[rank0]:     train_internal.training(
[rank0]:   File "/workspace/Grendel-GS/train_internal.py", line 46, in training
[rank0]:     scene = Scene(args, gaussians)
[rank0]:   File "/workspace/Grendel-GS/scene/__init__.py", line 131, in __init__
[rank0]:     self.train_cameras = cameraList_from_camInfos(train_cameras, args)
[rank0]:   File "/workspace/Grendel-GS/utils/camera_utils.py", line 226, in cameraList_from_camInfos
[rank0]:     loadCam(
[rank0]:   File "/workspace/Grendel-GS/utils/camera_utils.py", line 73, in loadCam
[rank0]:     return Camera(
[rank0]:   File "/workspace/Grendel-GS/scene/cameras.py", line 68, in __init__
[rank0]:     self.original_image_backup = self.original_image_backup.to("cuda")
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU 0 has a total capacity of 79.11 GiB of which 48.69 MiB is free. Process 3626438 has 68.36 GiB memory in use. Process 860419 has 9.15 GiB memory in use. Process 860421 has 520.00 MiB memory in use. Process 860420 has 520.00 MiB memory in use. Process 860422 has 520.00 MiB memory in use. Of the allocated memory 5.80 GiB is allocated by PyTorch, and 192.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
W1225 01:15:06.045000 165690 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 165757 closing signal SIGTERM
W1225 01:15:06.045000 165690 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 165758 closing signal SIGTERM
W1225 01:15:06.046000 165690 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 165759 closing signal SIGTERM
E1225 01:15:07.977000 165690 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 165756) of binary: /root/miniconda3/envs/grendel/bin/python3.10
Traceback (most recent call last):
  File "/root/miniconda3/envs/grendel/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/grendel/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/grendel/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/root/miniconda3/envs/grendel/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/root/miniconda3/envs/grendel/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/grendel/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-25_01:15:06
  host      : irina3dgs-547b45-dlpfc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 165756)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

Very curious to see if anyone has experienced something similar.

**Comment by GBncywang** [comment]
This was resolved through using preload_dataset_to_gpu_threshold 0 to prevent images from being pre-loaded to GPU, which results in the OOM.
